### ISSUE TITLE
Solr key suggestions disappear when auth token stale

### ISSUE THREAD

**Issue by jcreel** [TAMULib/SAGE#103]
Reproduce by lingering on the DV create or edit modal

**Comment by wwelling** [comment]
Unable to reproduce as described. I did however experience a complete page refresh when opening the create or edit discovery view modal when the token has expired.

**Comment by jsavell** [comment]
I haven't been able to recreate the issue, but some observations:

Both dev and pre solrs are locked down again, so Sage can't read the solrs to get the keys for those sources.

Sage received a Weaver upgrade a month ago, so if that's been deployed, it may have fixed the issue.
