### ISSUE TITLE
Post authentication redirect to last view breaks when deployed under context path

### ISSUE THREAD

**Issue by wwelling** [TAMULib/SAGE#155]
Reproduce:

when not logged in
- goto splash page
- click manage
- click login from unauthorized view

referrer redirect back from service provider is missing context path

```
https://labs.library.tamu.edu/management/internal-metadata?jwt=[token]
```

https://github.com/TAMULib/Weaver-UI-Core/blob/2.x/app/controllers/authenticationController.js#L62

**Comment by jcreel** [comment]
This will need an accompanying Weaver UI Core card.
