### ISSUE TITLE
Add button for search

### ISSUE THREAD

**Issue by jcreel** [TAMULib/SAGE#194]
This will improve UX and accessibility.  See this Abstract link:
https://app.abstract.com/projects/4e87881f-280d-4b2c-a8ca-64544767c83c/branches/e5763f6b-534d-444c-94b2-3b6619a3e79a/commits/5a294774bf5b7999640115992b6940d518caac8c/files/981be65f-ac61-4e43-82e5-719cd7daa49d/layers/711660A6-D5F9-4D1C-9379-0EA4A12635F8?collectionId=62a84697-19c9-4198-b727-a1e6a5d1938a&collectionLayerId=a6249814-683a-47d3-8b34-e8f3b5104e00&present=true&preview=false&sha=5a294774bf5b7999640115992b6940d518caac8c

**Comment by jsavell** [comment]
Also in this issue, we're maintaining search field context between searches.
