### ISSUE TITLE
Add facet selections to the display below search box in order they are selected

### ISSUE THREAD

**Issue by jcreel** [TAMULib/SAGE#212]

**Comment by jsavell** [comment]
This behavior seems to be in place already.

In both Firefox and Chrome, the facet selections appear in the order they're added, with the newest on the left and the oldest on the right.

**Comment by jsavell** [comment]
On the other hand, this doesn't appear to be the case on demos:
https://demos.library.tamu.edu/sage/discovery-context/berger-cloonan?f.genre=Tiger%20eye%20marbled%20papers&f.content_type=StillImage

**Comment by wwelling** [comment]
It seems they re-order the applied filters in the same order as the facets on the sidebar.

**Comment by wwelling** [comment]
This does not look like it will be an easy feature.

https://github.com/TAMULib/SAGE/blob/master/src/main/java/edu/tamu/sage/service/SolrDiscoveryService.java#L109

They are applied as selected on the front end, but the back end rebuilds the applied filters in the order of the facets on the discovery context.
