### ISSUE TITLE
Take off icons from breadcrumbs and make text color neutral

### ISSUE THREAD

**Issue by davelowetx** [TAMULib/SAGE#213]

**Comment by jcreel** [comment]
Take off the icons, take off the grey and blue on the breadcrumbs.  Comp can be seen at: https://app.abstract.com/share/ec3cd287-916e-4fa7-9fdd-e652e8f59235?collectionId=62a84697-19c9-4198-b727-a1e6a5d1938a&collectionLayerId=34f1b934-7bd1-4d8b-a87d-e8e964167961&present=true&preview=false&sha=b82e09cd581d599dc94bd363ff605f2fcf101f94
