### ISSUE TITLE
Create Accounts Using Common DI Credentials

### ISSUE THREAD

**Issue by jeremythuff** [TAMULib/SAGE#291]
We should have a DI email that allows us to have accounts with the following services:

- [ ] Github
- [ ] Coveralls
- [ ] Lighthouse
- [ ] Repo Administrative Membership (Secret Name for workflows)

This required a Helpdesk ticket be created for the email address. This ticket has been created and is now in process.

**Comment by kaladay** [comment]
I just noticed that this is in the "Done" column.
Confirm the status of this and close appropriately.
