### ISSUE TITLE
As a user, I want to be able to download related files as I view DSpace maps in SAGE

### ISSUE THREAD

**Issue by jcreel** [TAMULib/SAGE#301]
These would include georeferenced files and zip files.  The links should be user friendly and accessible.  For the purposes of the card, consider links to DSpace bitstreams on this pass.

Future cards will consider Spotlight collections, Mirador views, and provision of pdfs for the resources.

This card will be considered complete with the completion of DSpace#183.  For the purposes of this card, the links can simply be shown in the metadata with appropriate glosses.

**Comment by wwelling** [comment]
For Fedora, the Solr document transform will have to be updated to pick out resources within the container.

**Comment by wwelling** [comment]
Are DSpace Item bitstreams being indexed into Solr?

**Comment by jsavell** [comment]
I could easily be wrong here, but it looks like the FullText bitstreams are the only ones that have some of their data written to the solr index:

https://github.com/TAMULib/DSpace/blob/tamu-dspace-6.3/dspace-api/src/main/java/org/dspace/discovery/SolrServiceImpl.java#L942

**Comment by jsavell** [comment]
Looks like the bitstream info in the search and single item views comes from the mets.xml, not solr.

https://github.com/TAMULib/DSpace/blob/tamu-dspace-6.3/dspace-xmlui-mirage2/src/main/webapp/xsl/aspect/artifactbrowser/item-view.xsl#L70

https://github.com/TAMULib/DSpace/blob/tamu-dspace-6.3/dspace-xmlui-mirage2/src/main/webapp/xsl/aspect/artifactbrowser/item-list.xsl#L187

https://dspacepre1.library.tamu.edu//metadata/handle/1969.1/189041/mets.xml

**Comment by jcreel** [comment]
For the DSpace case:
https://github.com/TAMULib/DSpace/blob/tamu-dspace-6.3/dspace/modules/additions/src/main/java/org/dspace/discovery/SolrServiceImpl.java#L1002 could potentially be enhanced to write the bitstream data.
Alternatively, we could put the related bitstreams into a generated IIIF Manifest.

**Comment by jcreel** [comment]
Size this supposing that we put the Primary bitstream into its own single-value Solr field.  Other files in ORIGINAL bundle would go in a multi-valued Solr field for related files.  Thumbnails would go in a multi-valued Solr field.  Licenses would go in another multi-valued Solr field.

**Comment by wwelling** [comment]
This may help https://github.com/TAMULib/DSpace/blob/tamu-dspace-6.3/dspace/modules/additions/src/main/java/org/dspace/content/ItemServiceImpl.java#L285
