### ISSUE TITLE
Modal does not close properly after selecting facet entry in the "more..." paginated modal

### ISSUE THREAD

**Issue by jcreel** [TAMULib/SAGE#350]
URL is set properly, but the page is greyed out and inaccessible.  Page body still has "modal-open" class and <div class="modal-backdrop fade in"></div> is still present.  Refreshing page is required to regain use.

**Comment by jsavell** [comment]
This looks a lot like: https://github.com/TexasDigitalLibrary/Vireo/pull/1507

SAGE also has an ng-if on the section containing the facet component.

I'm working on getting a Discovery View populates on my local SAGE to test if converting to ng-show will solve this too.
