### ISSUE TITLE
Delete of resources requires a page refresh to update lists

### ISSUE THREAD

**Issue by jeremythuff** [TAMULib/SAGE#455]
**Describe the bug**
When deleting one of the managed resources in SAGE (internal metadata, cores, readers, writers, operators, jobs or discovery views) the lists displaying the resource do not remove the item upon a successful deletion. The page must be refreshed before the item can be seen to have been removed.

**To Reproduce**
1. Go to https://demos.library.tamu.edu/sage/management/internal-metadata
2. Click on the trashcan icon for any of the listed internal meta data
3. Click on 'confirm' button
4. See that the deleted item is still displayed in the list of internal metadata
5. Refresh the page
6. See that the deleted item is no longer in the list of internal metadata, proving that the deletion had been successful

**Expected behavior**
The item should be removed from the list without the need for a page reset

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser chrome
 - Version 106.0.5249.119

**Comment by kaladay** [comment]
@jeremythuff I am having trouble reproducing on my Chrome.
I created a new item for testing on said server, refreshed page, and then deleted it.
The item disappeared without needing a page refresh.
A page refresh confirmed the item to be deleted.

I've also confirmed it to be working for me under Firefox.
