### ISSUE TITLE
Remove URL from Mirador single-item view

### ISSUE THREAD

**Issue by jcreel** [TAMULib/SAGE#491]
Look for solutions in tamu-mirador configuration or in the structure of the generated IIIF Manifest.

Text from customer:  

> The URL, and perhaps the 1 of 1, should be removed from the Mirador image viewer. This is taking up too much landscape and the link is ugly. The project tamu-mirador should be investigated to determine if a configuration may be found within.

**Comment by jcreel** [comment]
Could test Mirador here: https://demos.library.tamu.edu/mirador/
Could feed it manifests such as: https://api.library.tamu.edu/iiif-service/fedora/presentation/3b/6f/c3/25/3b6fc325-f6ca-41d8-b91e-8c5db3be8c13/time_of_resolve_objects/93

**Comment by kaladay** [comment]
Here is an example where the footer has something more than 1 of 1 and also has a much shorter file name.
- https://library.tamu.edu/discovery/discovery-context/geologic-atlas-united-states/Mi1lZWI3ZjNjNC1hOTQyLTQ3YmMtOTkzZi02ZDVhNjViMTYxOWQ=

**Comment by kaladay** [comment]
Created issue #509 to provide a solution derived from this investigation.
