### ISSUE TITLE
Use “OR” for whitespace separation instead of "AND"

### ISSUE THREAD

**Issue by jcreel** [TAMULib/SAGE#493]
Can do this at the level of the query builder in SAGE - possibly here https://github.com/TAMULib/SAGE/blob/main/src/main/java/edu/tamu/sage/service/SolrDiscoveryService.java#L142

**Comment by kaladay** [comment]
This does not require code changes.
It can be performed via the UI on the Discvery View by setting the **Default Operand**.

![Screenshot_2023-01-13_15-54-52](https://user-images.githubusercontent.com/35114839/212426497-b63a892f-f796-4123-bb46-9becb04c4f6a.png)
